import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Project TypeScript',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="pt-br">
          <head>
              <link
                  rel="icon"
                  href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100' fill='%23ffffff'%3E%3Ccircle cx='50' cy='50' r='50'/%3E%3Ctext x='50' y='60' font-size='60' text-anchor='middle' alignment-baseline='middle'%3E🌀%3C/text%3E%3C/svg%3E"
                  type="icon"
              />
          </head>
          <body className={inter.className}>{children}</body>
      </html>
  );
}
